### ISSUE TITLE
Beam is enforced to be Java 7 compatible

### ISSUE THREAD

**Issue by iemejia** [Kochava/beam-s3#1]
Thanks a lot for working on this one. I saw that a recent commit mounted the version to Java 8, but the code on Beam is enforced to be Java 7 compatible. Is there a strong reason to move this up ? If no maybe it is better to keep in version 7.

**Comment by jacobmarble** [comment]
I was having trouble using FluentIterables.from().filter() because the Predicate class in Guava 23 is weird by my experience. My IDE offered to switch to Java 8 with streams, so I clicked. :grimacing:

Looks like the Predicate class in Guava 20 is easier to implement, and it turns out that Beam also uses Guava 20, so there's the solution.

**Comment by iemejia** [comment]
+1, thanks.
